name: Deploy Frontend to Firebase Hosting

on:
  push:
    paths:
      - 'web/**'
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Build project (Next.js)
        run: |
          cd web
          npx next build

      - name: Verify .next folder
        run: |
          cd web
          if [ ! -d ".next" ]; then
            echo "❌ .next folder not found! Build failed?"
            exit 1
          fi
          echo "✔ .next folder exists"
          ls -la .next

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: agent-platfrom
          entryPoint: ./web
        run: echo "✅ Firebase deployment finished"
